<?php

namespace App\Enum;

enum Municipality :string
{
case Abuselim = 'أبوسليم';
case Obari = 'أوباري';
case Ojla = 'أوجلة';
case Ajkhra = 'اجخرة';
case Ajdabiya = 'إجدابيا';
case EdriAlShate = 'إدري الشاطئ';
case Asbia = 'اسبيعة';
case AlAbraq = 'الأبرق';
case AlAbyar = 'الأبيار';
case AlAsabia = 'الأصابعة';
case AlBardi = 'البردي';
case AlBariqa = 'البريقة';
case AlBaida = 'البيضاء';
case AlJufra = 'الجفرة';
case AlJamil = 'الجميل';
case AlHaraba = 'الحرابة';

case AlHawamid = 'الحوامد';
case AlKhums = 'الخمس';
case AlRajban = 'الرجبان';
case AlRahibat = 'الرحيبات';
case AlRiayna = 'الرياينة';
case AlZawia = 'الزاوية';

case AlZawiaAlJanoub = 'الزاوية الجنوب';
case AlZawiaAlGharb = 'الزاوية الغرب';
case AlZintan = 'الزنتان';
case AlZahra = 'الزهراء';
case AlZawyaAlSulatan = 'زوارة سلطان';
case AlSahia = 'الشرقية';
case AlSharqia = 'الشقيقة';
case AlSawr = 'السا��ح';
case AlShuwairif = 'الشويرف';
case AlAmeria = 'العامرية';
case AlAjilat = 'العجيلات';
case AlArban = 'العربان';
case AlAzizia = 'العزيزية';
case AlAwatah = 'العواته';
case AlGharifa = 'الغريفة';
case AlQuba = 'القبة';
case AlQarahBoulli = 'القرة بوللي';
case AlQardahAlShate = 'القرضة الشاطئ';
case AlQatrun = 'القطرون';
case AlQalaa = 'القلعة';
case AlQawalish = 'القواليش';
case AlQiqab = 'القيقب';

case AlKufra = 'الكفرة';
case AlMaiya = 'الماية';

case AlMarj = 'المرج';
case AlAwinah = 'العوينة';
case AlMamora = 'المعمورة';
case AlMilitania = 'المليطانية';
case AlManshiaAlJamil = 'المنشية الجميل';
case AlNasirah = 'النا��رية';
case Amsaad = 'امساعد';
case AntalatAlBaidan = 'انتلات البيضان';
case BirAlAshhab = 'بئر الأشهب';
case BatanAlJabal = 'باطن الجبل';
case BarakAlShate = 'براك الشاطئ';
case BintBia = 'بنت بية';
case Benghazi = 'بنغازي';
case BaniWalid = 'بني وليد';
case Tajoura = 'تاجوراء';
case Tazirbu = 'تازربو';
case Tawergha = 'تاورغاء';
case Taraghin = 'تراغن';
case Tarhuna = 'ترهونة';
case Tukra = 'توكرة';
case Jadu = 'جادو';
case Jalu = 'جالو';
case JardasAlAbid = 'جردس العبيد';
case Janzur = 'جنزور';
case SouthGreenMountain = 'جنوب الجبل الأخضر';
case HayAlAndalus = 'حي الأندلس';
case SidraGulf = 'خليج السدرة';
case Daraj = 'درج';
case Derna = 'درنة';
case Rabiana = 'ربيانة';
case Riqdalin = 'رقدالين';
case Zaltan = 'زلطن';
case Zliten = 'زليتن';
case Zamzam = 'زمزم';
case Zuwara = 'زوارة';
case SahelAlJabal = 'ساحل الجبل';
case Sabha = 'سبها';
case Sirte = 'سرت';
case Suluq = 'سلوق';
case SuwaniBinAdam = 'سواني بن أدم';
case Sousa = 'سوسة';
case SouqAlJuma = 'سوق الجمعة';
case SouqAlKhamis = 'سوق الخميس';
case Shahat = 'شحات';
case Sabratha = 'صبراتة';
case Surman = 'صرمان';
case Tobruk = 'طبرق';
case TripoliCenter = 'طرابلس المركز';
case DhaherAlJabal = 'ظاهر الجبل';
case OmarAlMukhtar = 'عمر المختار';
case AinZara = 'عين زارة';
case AinGhazala = 'عين غزالة';
case Ghat = 'غات';
case Ghadames = 'غدامس';
case Gharyan = 'غريان';
case QasrBinGhashir = 'قصر بن غشير';
case QasrKhyar = 'قصر خيار';
case Qaminis = 'قمينس';
case Kabaw = 'كاباو';
case Kikla = 'ككلة';
case Maradah = 'مرادة';
case Murzuq = 'مرزق';
case MarsaDafniya = 'مرسى دفنة';
case Mizda = 'مزدة';
case Msallata = 'مسلاتة';
case Misrata = 'مصراتة';
case Nalut = 'نالوت';
case Nesma = 'نسمة';
case Harawa = 'هراوة';
case WadiAlBawanis = 'وادي البوانيس';
case WadiAtba = 'وادي عتبة';
case Wazzin = 'وازن';
case Wardama = 'وردامة';
case Yafran = 'يفرن';
case UmmAlRizam = 'أم الرزم';
case AlJalieda = 'الجليدة';
case AlJadida = 'الجديدة';
case MadurAlZaytoun = 'مدور الزيتون';
case AlAwainat = 'العوينات';
case Tajarhi = 'تجرهي';
case AlMardum = 'المردوم';
case Tininay = 'تنيناي';
case AlQurayyat = 'القريات';
case Zalla = 'زلة';
case Barqin = 'برقن';
case Awal = 'اوال';
case Tahala = 'تهالة';
case Barkat = 'بركت';
case Sinawan = 'سيناون';
case Zuwaila = 'زويلة';
case RasAlTabl = 'راس الطبل';
case AlShaabaAdministrativeArea = 'المنطقة الادارية الشعبة';
case Jarma = 'جرمة';
case Qarara = 'قرارة';
case AlRaqeeba = 'الرقيبة';

    public function label(): string
    {
        return match ($this) {
            self::Abuselim => 'أبوسليم',
            self::Obari => 'أوباري',
            self::Ojla => 'أوجلة',
            self::Ajkhra => 'اجخرة',
            self::Ajdabiya => 'إجدابيا',
            self::EdriAlShate => 'إدري الشاطئ',
            self::Asbia => 'اسبيعة',
            self::AlAbraq => 'الأبرق',
            self::AlAbyar => 'الأبيار',
            self::AlAsabia => 'الأصابعة',
            self::AlBardi => 'البردي',
            self::AlBariqa => 'البريقة',
            self::AlBaida => 'البيضاء',
            self::AlJufra => 'الجفرة',
            self::AlJamil => 'الجميل',
            self::AlHaraba => 'الحرابة',
            self::AlHawamid => 'الحوامد',
            self::AlKhums => 'الخمس',
            self::AlRajban => 'الرجبان',
            self::AlRahibat => 'الرحيبات',
            self::AlRiayna => 'الرياينة',
            self::AlZawia => 'الزاوية',
            self::AlZawiaAlJanoub => 'الزاوية الجنوب',
            self::AlZawiaAlGharb => 'الزاوية الغرب',
            self::AlZintan => 'الزنتان',
            self::AlZahra => 'الزهراء',
            self::AlZawyaAlSulatan => 'زوارة سلطان',
            self::AlSahia => 'الشرقية',
            self::AlSharqia => 'الشقيقة',
            self::AlSawr => 'السائح',
            self::AlShuwairif => 'الشويرف',
            self::AlAmeria => 'العامرية',
            self::AlAjilat => 'العجيلات',
            self::AlArban => 'العربان',
            self::AlAzizia => 'العزيزية',
            self::AlAwatah => 'العواته',
            self::AlGharifa => 'الغريفة',
            self::AlQuba => 'القبة',
            self::AlQarahBoulli => 'القرة بوللي',
            self::AlQardahAlShate => 'القرضة الشاطئ',
            self::AlQatrun => 'القطرون',
            self::AlQalaa => 'القلعة',
            self::AlQawalish => 'القواليش',
            self::AlQiqab => 'القيقب',
            self::AlKufra => 'الكفرة',
            self::AlMaiya => 'الماية',
            self::AlMarj => 'المرج',
            self::AlAwinah => 'العوينة',
            self::AlMamora => 'المعمورة',
            self::AlMilitania => 'المليطانية',
            self::AlManshiaAlJamil => 'المنشية الجميل',
            self::AlNasirah => 'الناصرية',
            self::Amsaad => 'امساعد',
            self::AntalatAlBaidan => 'انتلات البيضان',
            self::BirAlAshhab => 'بئر الأشهب',
            self::BatanAlJabal => 'باطن الجبل',
            self::BarakAlShate => 'براك الشاطئ',
            self::BintBia => 'بنت بية',
            self::Benghazi => 'بنغازي',
            self::BaniWalid => 'بني وليد',
            self::Tajoura => 'تاجوراء',
            self::Tazirbu => 'تازربو',
            self::Tawergha => 'تاورغاء',
            self::Taraghin => 'تراغن',
            self::Tarhuna => 'ترهونة',
            self::Tukra => 'توكرة',
            self::Jadu => 'جادو',
            self::Jalu => 'جالو',
            self::JardasAlAbid => 'جردس العبيد',
            self::Janzur => 'جنزور',
            self::SouthGreenMountain => 'جنوب الجبل الأخضر',
            self::HayAlAndalus => 'حي الأندلس',
            self::SidraGulf => 'خليج السدرة',
            self::Daraj => 'درج',
            self::Derna => 'درنة',
            self::Rabiana => 'ربيانة',
            self::Riqdalin => 'رقدالين',
            self::Zaltan => 'زلطن',
            self::Zliten => 'زليتن',
            self::Zamzam => 'زمزم',
            self::Zuwara => 'زوارة',
            self::SahelAlJabal => 'ساحل الجبل',
            self::Sabha => 'سبها',
            self::Sirte => 'سرت',
            self::Suluq => 'سلوق',
            self::SuwaniBinAdam => 'سواني بن أدم',
            self::Sousa => 'سوسة',
            self::SouqAlJuma => 'سوق الجمعة',
            self::SouqAlKhamis => 'سوق الخميس',
            self::Shahat => 'شحات',
            self::Sabratha => 'صبراتة',
            self::Surman => 'صرمان',
            self::Tobruk => 'طبرق',
            self::TripoliCenter => 'طرابلس المركز',
            self::DhaherAlJabal => 'ظاهر الجبل',
            self::OmarAlMukhtar => 'عمر المختار',
            self::AinZara => 'عين زارة',
            self::AinGhazala => 'عين غزالة',
            self::Ghat => 'غات',
            self::Ghadames => 'غدامس',
            self::Gharyan => 'غريان',
            self::QasrBinGhashir => 'قصر بن غشير',
            self::QasrKhyar => 'قصر خيار',
            self::Qaminis => 'قمينس',
            self::Kabaw => 'كاباو',
            self::Kikla => 'ككلة',
            self::Maradah => 'مرادة',
            self::Murzuq => 'مرزق',
            self::MarsaDafniya => 'مرسى دفنة',
            self::Mizda => 'مزدة',
            self::Msallata => 'مسلاتة',
            self::Misrata => 'مصراتة',
            self::Nalut => 'نالوت',
            self::Nesma => 'نسمة',
            self::Harawa => 'هراوة',
            self::WadiAlBawanis => 'وادي البوانيس',
            self::WadiAtba => 'وادي عتبة',
            self::Wazzin => 'وازن',
            self::Wardama => 'وردامة',
            self::Yafran => 'يفرن',
            self::UmmAlRizam => 'أم الرزم',
            self::AlJalieda => 'الجليدة',
            self::AlJadida => 'الجديدة',
            self::MadurAlZaytoun => 'مدور الزيتون',
            self::AlAwainat => 'العوينات',
            self::Tajarhi => 'تجرهي',
            self::AlMardum => 'المردوم',
            self::Tininay => 'تنيناي',
            self::AlQurayyat => 'القريات',
            self::Zalla => 'زلة',
            self::Barqin => 'برقن',
            self::Awal => 'اوال',
            self::Tahala => 'تهالة',
            self::Barkat => 'بركت',
            self::Sinawan => 'سيناون',
            self::Zuwaila => 'زويلة',
            self::RasAlTabl => 'راس الطبل',
            self::AlShaabaAdministrativeArea => 'المنطقة الادارية الشعبة',
            self::Jarma => 'جرمة',
            self::Qarara => 'قرارة',
            self::AlRaqeeba => 'الرقيبة',
        };
    }
}

